#!/usr/bin/env bash

IMAGE_NAME="${REGISTRY}/${REPOSITORY}"
RUBY_MINIOR_VERSION=${RUBY_VERSION%.*}
PYTHON_MINIOR_VERSION=${PYTHON_VERSION%.*}

TAGS="${IMAGE_NAME}:${RUBY_VERSION}-${VARIANT}-py${PYTHON_VERSION}"
TAGS="${TAGS},${IMAGE_NAME}:${RUBY_MINIOR_VERSION}-${VARIANT}-py${PYTHON_MINIOR_VERSION}"

echo $MAJOR_VARIANT
if [ "${MAJOR_VARIANT}" = "yes" ]; then
  TAGS="${TAGS},${IMAGE_NAME}:${RUBY_VERSION}-py${PYTHON_VERSION}"
  TAGS="${TAGS},${IMAGE_NAME}:${RUBY_MINIOR_VERSION}-py${PYTHON_MINIOR_VERSION}"
fi

echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
