name: Build

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - name: bookworm
        ruby:
          - version: '3.3.3'
        python:
          - version: '3.12.1'
            gpg: 7169605F62C751356D054A26A821E680E5FA6305

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            VARIANT=${{ matrix.variant.name }}
            RUBY_VERSION=${{ matrix.ruby.version }}
            PYTHON_VERSION=${{ matrix.python.version }}
            PYTHON_GPG_KEY=${{ matrix.python.gpg }}
          tags: |
            ${{ env.IMAGE_NAME }}:${ matrix.ruby.version }-${{ matrix.variant.name }}-py${{ matrix.python.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
